const express = require('express')
const router = express.Router()
const apiController = require('../controller/apiController')
const authMiddleware = require('../authMiddleware')

// V1 APIs
router.post('/newUserSignup', apiController.newUserSignup)
router.post('/newMediatorSignup', apiController.newMediatorSignup)
router.post('/login', apiController.login)
router.post('/refresh-token', apiController.refreshToken)
router.get('/getUserData', authMiddleware, apiController.getUserData)
router.post('/verify-signature', authMiddleware, apiController.verifySignature)
router.get('/scheduleMeeting', authMiddleware, apiController.scheduleMeeting)
router.get('/getDashboardContent', authMiddleware, apiController.getDashboardContent)
router.get('/logout', apiController.logout)
router.post('/updateInactiveUser', authMiddleware, apiController.updateInactiveUser)
router.get('/authenticateWithGoogle', authMiddleware, apiController.authenticateWithGoogle)
router.get('/googleCallback', apiController.googleCallback)
router.post('/newCalendarEvent', authMiddleware, apiController.newCalendarEvent)
router.post('/resetPassword', apiController.resetPassword)
router.post('/confirmPasswordChange', apiController.confirmPasswordChange)
router.get('/getAvailableLanguages', apiController.getAvailableLanguages)
router.get('/isEmailExist', apiController.isEmailExist)
router.get('/getInactiveUsers', authMiddleware, apiController.getInactiveUsers)
router.post('/saveNote', authMiddleware, apiController.saveNote)
router.post('/deleteNote', authMiddleware, apiController.deleteNote)
router.get('/getCalendarInit', authMiddleware, apiController.getCalendarInit)
router.get('/getMyCases', authMiddleware, apiController.getMyCases)
router.get('/getMyBlogs', authMiddleware, apiController.getMyBlogs)
router.post('/setClientPayment', authMiddleware, apiController.setClientPayment)
router.get('/getExistingUser', apiController.getExistingUser)
router.post('/saveBlog', authMiddleware, apiController.saveBlog)
router.get('/getBlogAssets', apiController.getBlogAssets)
router.post('/acceptMediationRequest', authMiddleware, apiController.acceptMediationRequest)
router.post('/newCase', authMiddleware, apiController.newCase)
// Temperory APIs
router.post('/sendemail/:email/:name', apiController.sendEmail)
router.get('/generatePassword', apiController.generatePassword)
router.get('/getActiveUsers', authMiddleware, apiController.getActiveUsers)
router.get('/getSignatureRequestDetails', apiController.getSignatureRequestDetails)
router.post('/submitSignature', apiController.submitSignature)
// Static website APIs
router.get('/getBlogs', apiController.geAllBlogs)
router.get('/getPublicBlogAssets', apiController.getPublicBlogAssets)
router.get('/getBlog', apiController.getBlog)
module.exports = router
